name: Retrain OTA

on:
  workflow_dispatch:
  push:
    paths:
      - 'corrections/**'

concurrency:
  group: retrain
  cancel-in-progress: true

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      

      - name: Install dependencies
        run: pip install tensorflow==2.18.0 numpy==2.0.2

      - name: Train
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: 1
        run: python train1.py

      - name: Upload model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model/mnist.keras
          retention-days: 30